### ISSUE TITLE
Missing docstrings

### ISSUE THREAD

**Issue by pradal** [openalea/eartrack#21]
On the reference documentation there are missing docstrings. Either exclude these functions or add adoc string (the latter action is recommended ;) )

In binarisation (http://eartrack.readthedocs.io/en/latest/source/references/binarisation.html):
- meanshift_hsv
- color_tree
- color_threshold_tree_cabin_1
NB: you can alias the last function with a better name

In eartrack, everything is documented. Congrat!!!
However, you can improve and homogeneize the docstring:
- This function analyses -> Analyse (Remove This function when possible)
- Recall for doc string: A first line as a summary. Then blank line. Then detail description of what the function do. 
**Modify get_view_angles**

**Comment by brichet** [comment]
OK thank, I'll do that.
Does readthedoc is automatically rebuild or do I have to do that myself ?
About the 2 functions color_threshold_tree_cabin_X , I have a script which automatically write the function from R decision tree description output. I have to implement that for more readability. New issue !

**Comment by pradal** [comment]
The doc is built as soon as the PR is merged. So, just change the code, and everything will work like a snap.
If the name modification of color_... is too complex, let it as is. This is just a detail.

**Comment by brichet** [comment]
This is not about the name modification, but about the function itself, which are not readable.
