### ISSUE TITLE
Enhance command line eartrack

### ISSUE THREAD

**Issue by pradal** [openalea/eartrack#8]
I think that OptParse is more enhanced than argparse.
What I propose is to replace (in main.py) argparse by OptParse
(see  [vclimb.py](https://github.com/VersionClimber/VersionClimber/tree/master/versionclimber/vclimb.py))
Then, I recommend to add a function main.py which will be called at command execution.

@brichet: What do you think about it?

**Comment by brichet** [comment]
I'm OK with your recommendations.
I'll do it as soon as possible.
